version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    networks:
      - app-network

  client_gateway:
    build: ./client_gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client_gateway/src:/usr/src/app/src
    command: "pnpm run start:dev"
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    networks:
      - app-network

 
###red

networks:
  app-network:
    driver: bridge
